[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:startup]
command=/bin/sh -c "php /var/www/html/artisan storage:link --force && php /var/www/html/artisan config:cache"
autostart=true
autorestart=false
startsecs=0
priority=1
stdout_logfile=/var/log/startup.log
stderr_logfile=/var/log/startup.log

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
priority=10

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=20